import {
  facebook,
  instagram,
  shieldTick,
  support,
  truckFast,
  twitter,
} from "../assets/icons";
import {
  bigShoe1,
  bigShoe2,
  bigShoe3,
  customer1,
  customer2,
  shoe4,
  shoe5,
  shoe6,
  shoe7,
  thumbnailShoe1,
  thumbnailShoe2,
  thumbnailShoe3,
} from "../assets/images";

export const navLinks = [
  { href: "/", label: "Home" },
  { href: "/Products", label: "Products" },
  { href: "/AboutUs", label: "About Us" },
  { href: "/ContactUs", label: "Contact Us" },
];

export const shoes = [
  {
    thumbnail: thumbnailShoe1,
    bigShoe: bigShoe1,
  },
  {
    thumbnail: thumbnailShoe2,
    bigShoe: bigShoe2,
  },
  {
    thumbnail: thumbnailShoe3,
    bigShoe: bigShoe3,
  },
];

export const statistics = [
  { value: "1k+", label: "Brands" },
  { value: "500+", label: "Shops" },
  { value: "250k+", label: "Customers" },
];

export const popularProducts = [
  {
    id: 1,
    imgURL: shoe6,
    name: "Shoe classic-1",
    price: "$200.50",
    rate: "4.6",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 2,
    imgURL: shoe5,
    name: "Shoe Air-2",
    price: "$201.00",
    rate: "4.7",
    description: "Engineered for peak performance and endurance.",
  },
  {
    id: 6,
    imgURL: shoe7,
    name: "Shoe Air-6",
    price: "$203.00",
    rate: "4.6",
    description: "Lightweight and breathable material for maximum comfort.",
  },
  {
    id: 7,
    imgURL: shoe4,
    name: "Shoe classic-7",
    price: "$203.50",
    rate: "4.7",
    description: "Modern design with a classic touch.",
  },
];

export const services = [
  {
    imgURL: truckFast,
    label: "Free shipping",
    subtext: "Enjoy seamless shopping with our complimentary shipping service.",
  },
  {
    imgURL: shieldTick,
    label: "Secure Payment",
    subtext:
      "Experience worry-free transactions with our secure payment options.",
  },
  {
    imgURL: support,
    label: "Love to help you",
    subtext: "Our dedicated team is here to assist you every step of the way.",
  },
];

export const reviews = [
  {
    imgURL: customer1,
    customerName: "Morich Brown",
    rating: 4.5,
    feedback:
      "The attention to detail and the quality of the product exceeded my expectations. Highly recommended!",
  },
  {
    imgURL: customer2,
    customerName: "Lota Mongeskar",
    rating: 4.5,
    feedback:
      "The product not only met but exceeded my expectations. I'll definitely be a returning customer!",
  },
];

export const footerLinks = [
  {
    title: "Products",
    links: [
      { name: "Air Force 1", link: "/" },
      { name: "Air Max 1", link: "/" },
      { name: "Air Jordan 1", link: "/" },
      { name: "Air Force 2", link: "/" },
      { name: "Shoe Waffle Racer", link: "/" },
      { name: "Shoe Cortez", link: "/" },
    ],
  },
  {
    title: "Help",
    links: [
      { name: "About us", link: "/" },
      { name: "FAQs", link: "/" },
      { name: "How it works", link: "/" },
      { name: "Privacy policy", link: "/" },
      { name: "Payment policy", link: "/" },
    ],
  },
  {
    title: "Get in touch",
    links: [
      { name: "customer@Shoe.com", link: "mailto:customer@Shoe.com" },
      { name: "+92554862354", link: "tel:+92554862354" },
    ],
  },
];

export const socialMedia = [
  { src: facebook, alt: "facebook logo" },
  { src: twitter, alt: "twitter logo" },
  { src: instagram, alt: "instagram logo" },
];

export const allProducts = [
  {
    id: 1,
    imgURL: shoe6,
    name: "Shoe classic-1",
    price: "$200.50",
    rate: "4.6",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 2,
    imgURL: shoe5,
    name: "Shoe Air-2",
    price: "$201.00",
    rate: "4.7",
    description: "Engineered for peak performance and endurance.",
  },
  {
    id: 3,
    imgURL: shoe5,
    name: "Shoe sport-3",
    price: "$201.50",
    rate: "4.8",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 4,
    imgURL: shoe4,
    name: "Shoe Air-4",
    price: "$202.00",
    rate: "4.9",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 5,
    imgURL: shoe5,
    name: "Shoe classic-5",
    price: "$202.50",
    rate: "4.5",
    description: "Versatile and trendy, complements any outfit.",
  },
  {
    id: 6,
    imgURL: shoe7,
    name: "Shoe Air-6",
    price: "$203.00",
    rate: "4.6",
    description: "Lightweight and breathable material for maximum comfort.",
  },
  {
    id: 7,
    imgURL: shoe4,
    name: "Shoe classic-7",
    price: "$203.50",
    rate: "4.7",
    description: "Modern design with a classic touch.",
  },
  {
    id: 8,
    imgURL: shoe6,
    name: "Shoe Air-8",
    price: "$204.00",
    rate: "4.8",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 9,
    imgURL: shoe5,
    name: "Shoe sport-9",
    price: "$204.50",
    rate: "4.9",
    description: "Modern design with a classic touch.",
  },
  {
    id: 10,
    imgURL: shoe7,
    name: "Shoe Air-10",
    price: "$205.00",
    rate: "4.5",
    description: "Perfect for sports and casual wear.",
  },
  {
    id: 11,
    imgURL: shoe5,
    name: "Shoe classic-11",
    price: "$205.50",
    rate: "4.6",
    description: "Modern design with a classic touch.",
  },
  {
    id: 12,
    imgURL: shoe7,
    name: "Shoe Air-12",
    price: "$206.00",
    rate: "4.7",
    description: "Lightweight and breathable material for maximum comfort.",
  },
  {
    id: 13,
    imgURL: shoe6,
    name: "Shoe classic-13",
    price: "$206.50",
    rate: "4.8",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 14,
    imgURL: shoe6,
    name: "Shoe Air-14",
    price: "$207.00",
    rate: "4.9",
    description: "Ideal for both professional athletes and everyday use.",
  },
  {
    id: 15,
    imgURL: shoe6,
    name: "Shoe sport-15",
    price: "$207.50",
    rate: "4.5",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 16,
    imgURL: shoe7,
    name: "Shoe Air-16",
    price: "$208.00",
    rate: "4.6",
    description: "Versatile and trendy, complements any outfit.",
  },
  {
    id: 17,
    imgURL: shoe7,
    name: "Shoe classic-17",
    price: "$208.50",
    rate: "4.7",
    description: "Versatile and trendy, complements any outfit.",
  },
  {
    id: 18,
    imgURL: shoe6,
    name: "Shoe Air-18",
    price: "$209.00",
    rate: "4.8",
    description: "Perfect for sports and casual wear.",
  },
  {
    id: 19,
    imgURL: shoe4,
    name: "Shoe classic-19",
    price: "$209.50",
    rate: "4.9",
    description: "Modern design with a classic touch.",
  },
  {
    id: 20,
    imgURL: shoe6,
    name: "Shoe Air-20",
    price: "$210.00",
    rate: "4.5",
    description: "High quality and comfortable running shoes.",
  },
  {
    id: 21,
    imgURL: shoe7,
    name: "Shoe sport-21",
    price: "$210.50",
    rate: "4.6",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 22,
    imgURL: shoe5,
    name: "Shoe Air-22",
    price: "$211.00",
    rate: "4.7",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 23,
    imgURL: shoe4,
    name: "Shoe classic-23",
    price: "$211.50",
    rate: "4.8",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 24,
    imgURL: shoe6,
    name: "Shoe Air-24",
    price: "$212.00",
    rate: "4.9",
    description: "Ideal for both professional athletes and everyday use.",
  },
  {
    id: 25,
    imgURL: shoe5,
    name: "Shoe classic-25",
    price: "$212.50",
    rate: "4.5",
    description: "Ideal for both professional athletes and everyday use.",
  },
  {
    id: 26,
    imgURL: shoe7,
    name: "Shoe Air-26",
    price: "$213.00",
    rate: "4.6",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 27,
    imgURL: shoe5,
    name: "Shoe sport-27",
    price: "$213.50",
    rate: "4.7",
    description: "Perfect for sports and casual wear.",
  },
  {
    id: 28,
    imgURL: shoe6,
    name: "Shoe Air-28",
    price: "$214.00",
    rate: "4.8",
    description: "Ideal for both professional athletes and everyday use.",
  },
  {
    id: 29,
    imgURL: shoe7,
    name: "Shoe classic-29",
    price: "$214.50",
    rate: "4.9",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 30,
    imgURL: shoe6,
    name: "Shoe Air-30",
    price: "$215.00",
    rate: "4.5",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 31,
    imgURL: shoe7,
    name: "Shoe classic-31",
    price: "$215.50",
    rate: "4.6",
    description: "Modern design with a classic touch.",
  },
  {
    id: 32,
    imgURL: shoe4,
    name: "Shoe Air-32",
    price: "$216.00",
    rate: "4.7",
    description: "High quality and comfortable running shoes.",
  },
  {
    id: 33,
    imgURL: shoe6,
    name: "Shoe sport-33",
    price: "$216.50",
    rate: "4.8",
    description: "Lightweight and breathable material for maximum comfort.",
  },
  {
    id: 34,
    imgURL: shoe7,
    name: "Shoe Air-34",
    price: "$217.00",
    rate: "4.9",
    description: "Versatile and trendy, complements any outfit.",
  },
  {
    id: 35,
    imgURL: shoe4,
    name: "Shoe classic-35",
    price: "$217.50",
    rate: "4.5",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 36,
    imgURL: shoe5,
    name: "Shoe Air-36",
    price: "$218.00",
    rate: "4.6",
    description: "Perfect for sports and casual wear.",
  },
  {
    id: 37,
    imgURL: shoe5,
    name: "Shoe classic-37",
    price: "$218.50",
    rate: "4.7",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 38,
    imgURL: shoe5,
    name: "Shoe Air-38",
    price: "$219.00",
    rate: "4.8",
    description: "High quality and comfortable running shoes.",
  },
  {
    id: 39,
    imgURL: shoe6,
    name: "Shoe sport-39",
    price: "$219.50",
    rate: "4.9",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 40,
    imgURL: shoe6,
    name: "Shoe Air-40",
    price: "$220.00",
    rate: "4.5",
    description: "Modern design with a classic touch.",
  },
  {
    id: 41,
    imgURL: shoe6,
    name: "Shoe classic-41",
    price: "$220.50",
    rate: "4.6",
    description: "Ideal for both professional athletes and everyday use.",
  },
  {
    id: 42,
    imgURL: shoe7,
    name: "Shoe Air-42",
    price: "$221.00",
    rate: "4.7",
    description: "Engineered for peak performance and endurance.",
  },
  {
    id: 43,
    imgURL: shoe7,
    name: "Shoe classic-43",
    price: "$221.50",
    rate: "4.8",
    description: "High quality and comfortable running shoes.",
  },
  {
    id: 44,
    imgURL: shoe7,
    name: "Shoe Air-44",
    price: "$222.00",
    rate: "4.9",
    description: "Perfect for sports and casual wear.",
  },
  {
    id: 45,
    imgURL: shoe6,
    name: "Shoe sport-45",
    price: "$222.50",
    rate: "4.5",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 46,
    imgURL: shoe7,
    name: "Shoe Air-46",
    price: "$223.00",
    rate: "4.6",
    description: "Engineered for peak performance and endurance.",
  },
  {
    id: 47,
    imgURL: shoe6,
    name: "Shoe classic-47",
    price: "$223.50",
    rate: "4.7",
    description: "Lightweight and breathable material for maximum comfort.",
  },
  {
    id: 48,
    imgURL: shoe5,
    name: "Shoe Air-48",
    price: "$224.00",
    rate: "4.8",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 49,
    imgURL: shoe6,
    name: "Shoe classic-49",
    price: "$224.50",
    rate: "4.9",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 50,
    imgURL: shoe7,
    name: "Shoe Air-50",
    price: "$225.00",
    rate: "4.5",
    description: "Engineered for peak performance and endurance.",
  },
  {
    id: 51,
    imgURL: shoe6,
    name: "Shoe sport-51",
    price: "$225.50",
    rate: "4.6",
    description: "High quality and comfortable running shoes.",
  },
  {
    id: 52,
    imgURL: shoe4,
    name: "Shoe Air-52",
    price: "$226.00",
    rate: "4.7",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 53,
    imgURL: shoe5,
    name: "Shoe classic-53",
    price: "$226.50",
    rate: "4.8",
    description: "Lightweight and breathable material for maximum comfort.",
  },
  {
    id: 54,
    imgURL: shoe4,
    name: "Shoe Air-54",
    price: "$227.00",
    rate: "4.9",
    description: "Versatile and trendy, complements any outfit.",
  },
  {
    id: 55,
    imgURL: shoe6,
    name: "Shoe classic-55",
    price: "$227.50",
    rate: "4.5",
    description: "Ideal for both professional athletes and everyday use.",
  },
  {
    id: 56,
    imgURL: shoe4,
    name: "Shoe Air-56",
    price: "$228.00",
    rate: "4.6",
    description: "Engineered for peak performance and endurance.",
  },
  {
    id: 57,
    imgURL: shoe4,
    name: "Shoe sport-57",
    price: "$228.50",
    rate: "4.7",
    description: "Versatile and trendy, complements any outfit.",
  },
  {
    id: 58,
    imgURL: shoe5,
    name: "Shoe Air-58",
    price: "$229.00",
    rate: "4.8",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 59,
    imgURL: shoe6,
    name: "Shoe classic-59",
    price: "$229.50",
    rate: "4.9",
    description: "Versatile and trendy, complements any outfit.",
  },
  {
    id: 60,
    imgURL: shoe7,
    name: "Shoe Air-60",
    price: "$230.00",
    rate: "4.5",
    description: "Perfect for sports and casual wear.",
  },
  {
    id: 61,
    imgURL: shoe5,
    name: "Shoe classic-61",
    price: "$230.50",
    rate: "4.6",
    description: "High quality and comfortable running shoes.",
  },
  {
    id: 62,
    imgURL: shoe7,
    name: "Shoe Air-62",
    price: "$231.00",
    rate: "4.7",
    description: "Modern design with a classic touch.",
  },
  {
    id: 63,
    imgURL: shoe7,
    name: "Shoe sport-63",
    price: "$231.50",
    rate: "4.8",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 64,
    imgURL: shoe7,
    name: "Shoe Air-64",
    price: "$232.00",
    rate: "4.9",
    description: "Versatile and trendy, complements any outfit.",
  },
  {
    id: 65,
    imgURL: shoe4,
    name: "Shoe classic-65",
    price: "$232.50",
    rate: "4.5",
    description: "Ideal for both professional athletes and everyday use.",
  },
  {
    id: 66,
    imgURL: shoe6,
    name: "Shoe Air-66",
    price: "$233.00",
    rate: "4.6",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 67,
    imgURL: shoe6,
    name: "Shoe classic-67",
    price: "$233.50",
    rate: "4.7",
    description: "High quality and comfortable running shoes.",
  },
  {
    id: 68,
    imgURL: shoe4,
    name: "Shoe Air-68",
    price: "$234.00",
    rate: "4.8",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 69,
    imgURL: shoe4,
    name: "Shoe sport-69",
    price: "$234.50",
    rate: "4.9",
    description: "Lightweight and breathable material for maximum comfort.",
  },
  {
    id: 70,
    imgURL: shoe7,
    name: "Shoe Air-70",
    price: "$235.00",
    rate: "4.5",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 71,
    imgURL: shoe4,
    name: "Shoe classic-71",
    price: "$235.50",
    rate: "4.6",
    description: "Lightweight and breathable material for maximum comfort.",
  },
  {
    id: 72,
    imgURL: shoe4,
    name: "Shoe Air-72",
    price: "$236.00",
    rate: "4.7",
    description: "Lightweight and breathable material for maximum comfort.",
  },
  {
    id: 73,
    imgURL: shoe7,
    name: "Shoe classic-73",
    price: "$236.50",
    rate: "4.8",
    description: "Engineered for peak performance and endurance.",
  },
  {
    id: 74,
    imgURL: shoe5,
    name: "Shoe Air-74",
    price: "$237.00",
    rate: "4.9",
    description: "Versatile and trendy, complements any outfit.",
  },
  {
    id: 75,
    imgURL: shoe6,
    name: "Shoe sport-75",
    price: "$237.50",
    rate: "4.5",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 76,
    imgURL: shoe4,
    name: "Shoe Air-76",
    price: "$238.00",
    rate: "4.6",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 77,
    imgURL: shoe5,
    name: "Shoe classic-77",
    price: "$238.50",
    rate: "4.7",
    description: "Engineered for peak performance and endurance.",
  },
  {
    id: 78,
    imgURL: shoe4,
    name: "Shoe Air-78",
    price: "$239.00",
    rate: "4.8",
    description: "Ideal for both professional athletes and everyday use.",
  },
  {
    id: 79,
    imgURL: shoe7,
    name: "Shoe classic-79",
    price: "$239.50",
    rate: "4.9",
    description: "High quality and comfortable running shoes.",
  },
  {
    id: 80,
    imgURL: shoe7,
    name: "Shoe Air-80",
    price: "$240.00",
    rate: "4.5",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 81,
    imgURL: shoe5,
    name: "Shoe sport-81",
    price: "$240.50",
    rate: "4.6",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 82,
    imgURL: shoe7,
    name: "Shoe Air-82",
    price: "$241.00",
    rate: "4.7",
    description: "Lightweight and breathable material for maximum comfort.",
  },
  {
    id: 83,
    imgURL: shoe6,
    name: "Shoe classic-83",
    price: "$241.50",
    rate: "4.8",
    description: "Ideal for both professional athletes and everyday use.",
  },
  {
    id: 84,
    imgURL: shoe6,
    name: "Shoe Air-84",
    price: "$242.00",
    rate: "4.9",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 85,
    imgURL: shoe4,
    name: "Shoe classic-85",
    price: "$242.50",
    rate: "4.5",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 86,
    imgURL: shoe4,
    name: "Shoe Air-86",
    price: "$243.00",
    rate: "4.6",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 87,
    imgURL: shoe5,
    name: "Shoe sport-87",
    price: "$243.50",
    rate: "4.7",
    description:
      "Advanced cushioning technology for superior impact absorption.",
  },
  {
    id: 88,
    imgURL: shoe7,
    name: "Shoe Air-88",
    price: "$244.00",
    rate: "4.8",
    description: "Engineered for peak performance and endurance.",
  },
  {
    id: 89,
    imgURL: shoe6,
    name: "Shoe classic-89",
    price: "$244.50",
    rate: "4.9",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 90,
    imgURL: shoe7,
    name: "Shoe Air-90",
    price: "$245.00",
    rate: "4.5",
    description: "Modern design with a classic touch.",
  },
  {
    id: 91,
    imgURL: shoe5,
    name: "Shoe classic-91",
    price: "$245.50",
    rate: "4.6",
    description: "High quality and comfortable running shoes.",
  },
  {
    id: 92,
    imgURL: shoe4,
    name: "Shoe Air-92",
    price: "$246.00",
    rate: "4.7",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 93,
    imgURL: shoe4,
    name: "Shoe sport-93",
    price: "$246.50",
    rate: "4.8",
    description: "Modern design with a classic touch.",
  },
  {
    id: 94,
    imgURL: shoe7,
    name: "Shoe Air-94",
    price: "$247.00",
    rate: "4.9",
    description: "Ideal for both professional athletes and everyday use.",
  },
  {
    id: 95,
    imgURL: shoe7,
    name: "Shoe classic-95",
    price: "$247.50",
    rate: "4.5",
    description: "Perfect for sports and casual wear.",
  },
  {
    id: 96,
    imgURL: shoe4,
    name: "Shoe Air-96",
    price: "$248.00",
    rate: "4.6",
    description: "Stylish and durable, suitable for all occasions.",
  },
  {
    id: 97,
    imgURL: shoe4,
    name: "Shoe classic-97",
    price: "$248.50",
    rate: "4.7",
    description: "Versatile and trendy, complements any outfit.",
  },
  {
    id: 98,
    imgURL: shoe4,
    name: "Shoe Air-98",
    price: "$249.00",
    rate: "4.8",
    description: "High quality and comfortable running shoes.",
  },
  {
    id: 99,
    imgURL: shoe7,
    name: "Shoe sport-99",
    price: "$249.50",
    rate: "4.9",
    description: "Ergonomically designed to provide excellent support.",
  },
  {
    id: 100,
    imgURL: shoe4,
    name: "Shoe Air-100",
    price: "$250.00",
    rate: "4.5",
    description: "Versatile and trendy, complements any outfit.",
  },
];
